config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root "homes#top"

  get "/home/about" => "homes#about"
  resources :users
  resources :books
end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
 

  has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
      <%= render 'books/book', book: @book %>
    <div class="menu">
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
    </div>
  <div class="col-xs-3"></div>
</div>

app/views/books/index.html.erb
<h2>User info</h2>

<h3>name</h3>

<h3>intoroduction</h3>

<%= form_with model: Book.new do |f| %>
  <h5>title</h5>
  <%= f.text_field :title %>
	
  <h5>opinion</h5>
  <%= f.text_area :body %>
	
  <br><%= f.submit 'create book' %></br>
  
<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
  <h1>
  <p class="text-center">
  Welcom to 
  <i class="bi bi-book">
  Bookers!!
  </i>
  </h1>
  </p>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
	<div class="col-md-6 col-md-offset-3">
	  <div class="center-block">
	  	 <p class="text-center">
		<h1>Welcom to
		  <i class="bi bi-book"><b>Bookers!!</b></i>
		</h1>
		<p style="line-height:2rem">In
		  <i class="bi bi-book"><b>Bookers</b></i>,<br>
		  	you can share and exchange your opinions , inpresiions , and emotions<p style="line-height:2rem">about various books!</p>
		　</p>
	  </div>
	<div class="row">
      <%= link_to "Log in", new_user_session_path, class:"btn btn-primary col-xs-10 col-xs-offset-1" %>
	</div>
	<div class="row">
	  <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1" %>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
       <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
  </head>

<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
          <a class="navbar-brand p-1" href="/"><stong>Bookers</stong></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            
            <li class="">
              <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
              <i class="bi bi-house-fill"> Home</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to  users_path, class: 'nav-link text-white' do %>
              <i class="bi bi-people-fill"> Users</i>
              <% end %>
            </li>
            
            <li class="">
              <%= link_to  books_path, class: 'nav-link text-white' do %>
              <i class="bi bi-book-fill"> Books</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to  destroy_user_session_path,  method: :delete,class: 'nav-link text-white' do %>
              <i class="bi bi-box-arrow-right"> Log out</i>
              <% end %>
            </li>
            <% else %>
            <li class="">
              <%= link_to root_path, class: 'nav-link text-white' do %>
              <i class="bi bi-house-fill"> Home</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to home_about_path, class: 'nav-link text-white' do %>
              <i class="bi bi-link-45deg"> About</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
              <i class="bi bi-person-plus"> Sign up</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
              <i class="bi bi-box-arrow-in-right"> Log in</i>
              <% end %>
            </li>
            
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <%= yield %>
  <footer>
    <p class="text-centar"> CopyRight Infratop.inc</p>
  </footer>
 </body>
</html>

app/views/users/index.html.erb
<h1>inde</h1>